In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)


In [4]:
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [5]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [6]:
independent=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dependent=dataset[['Purchased']]

In [7]:
#split train and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)


In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [9]:
#model creation
from sklearn.ensemble import RandomForestClassifier 
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train, Y_train) 

Fitting 5 folds for each of 12 candidates, totalling 60 fits


E:\anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "E:\anaconda\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "E:\anaconda\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "E:\anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_paramet

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [10]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, grid_predictions)



In [11]:
print(grid.best_params_)

{'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}


In [12]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.001435      0.000735         0.000000        0.000000   
1        0.001092      0.000805         0.000000        0.000000   
2        0.030901      0.002309         0.010466        0.001129   
3        0.792126      0.233541         0.146408        0.042320   
4        0.028657      0.001954         0.009760        0.001072   
5        1.037374      0.397054         0.103220        0.047573   
6        0.002463      0.001722         0.000000        0.000000   
7        0.001578      0.001565         0.000000        0.000000   
8        0.219095      0.186586         0.095406        0.073835   
9        1.936237      0.086512         0.079434        0.027226   
10       0.362162      0.048179         0.064965        0.021384   
11       1.496243      0.056538         0.043449        0.022466   

   param_criterion param_max_features  param_n_estimators  \
0             gini               auto                  10   
1             gini               auto                 100   
2             gini               sqrt                  10   
3             gini               sqrt                 100   
4             gini               log2                  10   
5             gini               log2                 100   
6          entropy               auto                  10   
7          entropy               auto                 100   
8          entropy               sqrt                  10   
9          entropy               sqrt                 100   
10         entropy               log2                  10   
11         entropy               log2                 100   

                                               params  split0_test_score  \
0   {'criterion': 'gini', 'max_features': 'auto', ...                NaN   
1   {'criterion': 'gini', 'max_features': 'auto', ...                NaN   
2   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.764706   
3   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.764706   
4   {'criterion': 'gini', 'max_features': 'log2', ...           0.764706   
5   {'criterion': 'gini', 'max_features': 'log2', ...           0.764706   
6   {'criterion': 'entropy', 'max_features': 'auto...                NaN   
7   {'criterion': 'entropy', 'max_features': 'auto...                NaN   
8   {'criterion': 'entropy', 'max_features': 'sqrt...           0.727273   
9   {'criterion': 'entropy', 'max_features': 'sqrt...           0.800000   
10  {'criterion': 'entropy', 'max_features': 'log2...           0.764706   
11  {'criterion': 'entropy', 'max_features': 'log2...           0.800000   

    split1_test_score  split2_test_score  split3_test_score  \
0                 NaN                NaN                NaN   
1                 NaN                NaN                NaN   
2            0.789474           0.790698           0.871795   
3            0.850000           0.809524           0.900000   
4            0.810811           0.790698           0.864865   
5            0.871795           0.809524           0.900000   
6                 NaN                NaN                NaN   
7                 NaN                NaN                NaN   
8            0.742857           0.809524           0.864865   
9            0.842105           0.809524           0.900000   
10           0.820513           0.780488           0.871795   
11           0.842105           0.790698           0.900000   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0                 NaN              NaN             NaN                9  
1                 NaN              NaN             NaN                9  
2            0.888889         0.821112        0.049538                7  
3            0.923077         0.849461        0.057883                4  
4            0.888889         0.823994        0.046215                6  
5            0.947368         0.858679        0.064796                1 

In [13]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}: 0.9256751954513149


In [18]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[79  6]
 [ 4 45]]


In [20]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.95      0.93      0.94        85
           1       0.88      0.92      0.90        49

    accuracy                           0.93       134
   macro avg       0.92      0.92      0.92       134
weighted avg       0.93      0.93      0.93       134



In [22]:
table_pr=pd.DataFrame()

In [24]:
print(X_test)

[[-0.76605872  0.52531653  1.00754728]
 [ 0.02298918 -0.57354963 -0.99250926]
 [-0.27290378  0.16892751  1.00754728]
 [-0.76605872  0.28772385 -0.99250926]
 [-0.27290378 -0.57354963 -0.99250926]
 [-1.06195168 -1.4645222   1.00754728]
 [-0.66742773 -1.61301763 -0.99250926]
 [-0.1742728   2.21816441  1.00754728]
 [-1.94963056 -0.03896609 -0.99250926]
 [ 0.91066806 -0.78144323  1.00754728]
 [-0.76605872 -0.60324872  1.00754728]
 [-0.96332069 -0.42505421 -0.99250926]
 [-0.07564181 -0.42505421  1.00754728]
 [ 0.12162016  0.22832568  1.00754728]
 [-1.75236858  0.49561745  1.00754728]
 [-0.56879674  1.4162891  -0.99250926]
 [-0.07564181  0.22832568  1.00754728]
 [-1.85099957  0.46591836  1.00754728]
 [ 1.69971595  1.80237721 -0.99250926]
 [-0.27290378 -1.40512403  1.00754728]
 [-0.27290378 -0.66264689 -0.99250926]
 [ 0.91066806  2.21816441 -0.99250926]
 [ 0.31888214 -0.54385055 -0.99250926]
 [ 0.91066806  1.05990007  1.00754728]
 [-1.45647562 -1.22692951 -0.99250926]
 [ 1.10793003  2.12906715

In [26]:
table_pr['Age']=X_test["Age"]
table_pr['Gender_male']=X_test["Gender_Male"]
table_pr['Estimated_Salary']=X_test["EstimatedSalary"]
table_pr['Actual']=y_test
table_pr['Predicted']=grid_predictions

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [28]:
table_pr.head(134)

Empty DataFrame
Columns: []
Index: []

In [30]:
table_pr.to_csv("cm.csv",index=False)

In [40]:
age_input=float(input("Age:"))
bmi_input=float(input("EstimatedSalary:"))
sex_male_input=int(input("Gender_Male:"))

Age: 25
EstimatedSalary: 53
Gender_Male: 0


In [42]:
Future_Prediction=grid.predict([[age_input,bmi_input,sex_male_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]
